const mongoose=require('mongoose');
 
const CommentSchema=new mongoose.Schema(
    {

        content:{
           type:String,
           required:true
        },
        user:{
            type:mongoose.Schema.Types.ObjectId,
             ref:'User'
        },
        post:{
            // An ObjectID is a unique 12-byte identifier which can be generated by MongoDB as the primary key (_id) for a collection
            // To specify a type of ObjectId, use Schema.Types.ObjectId in your declaration.
            type:mongoose.Schema.Types.ObjectId,
            ref:'Post'
        },
        likes:[
            {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Like'
            },
        ]
    },{timestamps:true}
);

const Comment=mongoose.model('Comment',CommentSchema);
module.exports=Comment;